### ISSUE TITLE
Board position is not displaying on board-of-directors page for some members

### ISSUE THREAD

**Issue by lovestulip** [OpenSourceOrg/dotOrg#144]
### Issue

Our partner has reported an issue on the following page: https://opensource.org/about/board-of-directors

The board position "Chair" for Tracy Hinds is not displaying on the page: https://d.pr/i/8bhfZY

I think this issue is coming from [here](https://github.com/OpenSourceOrg/dotOrg/blob/d4f9561b5f1e9ec6174ab1f2b7b9ef73fb619874/themes/osi/template-parts/content-archive-board-member.php#L22). It appears that the display of the board position (member-position) is currently dependent on the pronouns field. Tracy Hinds does not have that field filled out. See: https://d.pr/i/2co6zO

You can review here: https://opensource.org/wp-admin/post.php?post=2929&action=edit

The condition that checks if the board_position field exists is "nested" inside the check for pronouns.

Strangely, her board position does displayed on her profile page: https://opensource.org/board-member/tracy-hinds

Could there be additional conditions to consider?
 
Can we please make sure the member position is displayed independently of pronouns? 

Please be sure to first do this on staging for our partner to review the changes. 

### Context

See ZD link on the internal dev request.

**Comment by gin0115** [comment]
Ive tracked it down to [here](https://github.com/OpenSourceOrg/dotOrg/blob/d4f9561b5f1e9ec6174ab1f2b7b9ef73fb619874/themes/osi/functions.php#L374), not sure why but we seem to be setting the max number of posts as 

```
How posts per page is worked out
= -1 + ( ({current page number} - 1 ) * 12)
// Becomes
= -1 + ( (0 - 1 ) * 12)
= -1 + -12
= 11
```
So even though there are 12 results on the board page, it is only showing 11. Im not sure why this logic exists, i dont want to just change it as i dont know why its even here. This was added in back in 2021 when the site was intially setup.

What im going to do is add a means to shortcircuit this, so we can ignore this and ensure it always shows all.

**Comment by smaffulli** [comment]
If that logic covers the blog posts, I can think that the reason is for the
landing page of the *blog* which shows a featured post up top and the
latest posts below. Maybe that's why?

this issue wasn't visible on the board archive because we used to have 10
board directors and now we have 12.

**Comment by gin0115** [comment]
@smaffulli 

Ahh, that makes sense, it seems to be applying to various query loops elsewhere on the site. I will tweak this to only apply to the `/blog` archive and not any other pages that have query loops in them 

Thanks for that insight @smaffulli :)

**Comment by gin0115** [comment]
@smaffulli

We have deployed this to staging now and it all seems to be working as expected (i added a test board member on [staging](https://open-source-initiative-development.mystagingwebsite.com/about-3/board-of-directors) to show 12)

I will get this deployed to production today

**Comment by smaffulli** [comment]
Hi Glynn, the 12 on staging look alright but I see the directors are on
2-column view while in production we have a better 3-column.
https://opensource.org/about/board-of-directors

did the patch change the arrangement of the archive?

**Comment by smaffulli** [comment]
Awesome, thanks!

**Comment by gin0115** [comment]
We have deployed this
https://github.com/OpenSourceOrg/dotOrg/blob/935953b2c7f2e81c4f70630c26ce56ec90701088/themes/osi/functions.php#L379
Might need to clear out any caches that could be caching that page, but hopefully this resolves the issue

**Comment by lovestulip** [comment]
@gin0115 I'm not seeing the changes applied to this page just yet: https://opensource.org/about/board-of-directors

> Might need to clear out any caches that could be caching that page, but hopefully this resolves the issue

I purged the edge cache and this issue still persists. Is there another cache that could be an issue?

**Comment by securityjedi** [comment]
Monitoring this for the next week. cc: @gin0115

**Comment by gin0115** [comment]
I got sidetracked with the missing members, and I glossed over the issue with pronouns and roles being shown.

This has been patched on staging
![image](https://github.com/user-attachments/assets/327f44d3-88d6-4e2d-992d-49d38c151f4a)

Will get a PR for main setup

**Comment by securityjedi** [comment]
This was pushed to production.

**Comment by lovestulip** [comment]
I'll close this one out as this is now resolved.
